### ISSUE TITLE
Is it real-time or rendering from a recorded data?

### ISSUE THREAD

**Issue by Lukikay** [keijiro/Akvfx#13]
Hi, this project is so awesome! I'm quite interested in it! 

I'm wondering if this is real-time with an Azure Kinect or it's just rendering from a recorded RGB/depth data?

And I'm also very interested in the VFX that from your projects Skinner/Smrvfx/DkvfxSketches that have more fancy particle effects. So are they using a similar framework and possible to have those VFX here?

**Comment by keijiro** [comment]
Akvfx = realtime
Dkvfx = recorded (using Depthkit)

https://github.com/keijiro/Dkvfx

>  So are they using a similar framework and possible to have those VFX here?

Skinner - Legacy. Don't use it.
Smrvfx - VFX Graph
DkvfxSketches - VFX Graph

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
