### ISSUE TITLE
documentation for creating effect

### ISSUE THREAD

**Issue by QuinnCiccoretti** [keijiro/Akvfx#14]
Hello,
Is there any documentation on how to create a new effect? I'm having trouble using the VFX property binder to set the value of particle positions. Thanks

**Comment by keijiro** [comment]
Sorry for the lack of documentation. I can't speak English, so writing good documentation is a thing like heavy lifting to me.

I'd recommend learning how to use the standard property binders first.

https://docs.unity3d.com/Packages/com.unity.visualeffectgraph@7.1/manual/PropertyBinders.html

**Comment by QuinnCiccoretti** [comment]
Thank you, I appreciate the help.
