### ISSUE TITLE
Reading only color frame

### ISSUE THREAD

**Issue by xubi1993** [keijiro/Akvfx#20]
Hello,
         Great asset, works very well but can you guide me how can I get the 2D camera color image inside the vfx graph. Here it computes the depth frame and depth color frame. I just want a normal color frame with no depth. How can I compute that. Is is even possible? Sorry I am not very good with shaders. Any help will be much appreciated.

Regards,
Zubair

**Comment by keijiro** [comment]
You can simply sample the color map using the Sample Texture2D operator.

**Comment by xubi1993** [comment]
I tried it but it does not appear like it does in 3D. It does not create a plane of 2D particles with the image from camera mapped on top of those particles. For example like this: https://www.youtube.com/watch?v=l5mZgdNeZD4

**Comment by xubi1993** [comment]
Thanks I got it, I just need to set the UV's right!
