### ISSUE TITLE
Unity NuGet not available

### ISSUE THREAD

**Issue by lacouture100** [keijiro/Akvfx#22]
Thank you for your work Keijiro-san,

This dependency link doesn't seem to be available. Is there any other source where I could obtain the package in order to be able to use your repository?

```
{
      "name": "Unity NuGet",
      "url": "https://unitynuget-registry.azurewebsites.net",
      "scopes": [
        "org.nuget"
      ]
    }

```

Thank you.

**Comment by lacouture100** [comment]
I have obtained the package from a previous version from the package cache of another project.

**Comment by keijiro** [comment]
This error was caused by the UnityNuGet registry. The issue has been already fixed.
