### ISSUE TITLE
DllNotFoundException: k4a

### ISSUE THREAD

**Issue by leeprobert** [keijiro/Akvfx#25]
Am just running the project as-is from your repo, and I get this error. Do I need to build the Azure Kinect SDK on my machine?

**Comment by leeprobert** [comment]
I wonder if this is because I am on a Mac running the new M1 chip though too?

**Comment by keijiro** [comment]
Please check the system requirements section on README and a linked page on Azure Kinect DK.

Quick answer: Azure Kinect DK doesn't support Mac.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
