### ISSUE TITLE
Kinect Error 

### ISSUE THREAD

**Issue by caoyuxistudio** [keijiro/Akvfx#31]
Dear Keijiro 
Working on this error whole day still haven't find solution , try both 2019.3.5 / 3.9 / 4.8
Error: Could not load signature of Microsoft.Azure.Kinect.Sensor.Allocator:GetManagedAllocatedMemory due to: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:(null) signature:<none>

See the screenshot belowed
![qwe](https://user-images.githubusercontent.com/6113335/136198393-b09e3adb-3d53-4b87-844e-c37e8ad3ef46.png)
:

**Comment by axistudio** [comment]
![qwe](https://user-images.githubusercontent.com/6113335/136198347-5ae034c0-b5d0-4bee-82fc-fac8e5af81ce.png)

**Comment by keijiro** [comment]
How about the sample project? Could you clone this repository and try opening it with 2019.4.8?

**Comment by caoyuxistudio** [comment]
Same error on example project, little context and hunch maybe, i am currently in China , so i can not successful ping the unity azure net server. could that be related to the issue?
![Screenshot 2021-10-06 211112](https://user-images.githubusercontent.com/6113335/136210021-a0e772bc-6341-43d2-b1d8-d9cb28d83702.png)

![image](https://user-images.githubusercontent.com/6113335/136209710-2c8e71b7-25b2-4858-9095-8a1b141cc6b8.png)

**Comment by keijiro** [comment]
Uh-oh, the server is not reachable from Japan, either. It seems like rebooting now. Please wait for a while, or ping them via Issues: https://github.com/xoofx/UnityNuGet

**Comment by keijiro** [comment]
It seems like up now. Please retry reopening the project.

**Comment by keijiro** [comment]
I'm pretty sure that it works as intended now. Please feel free to reopen this issue if it still reproduces on your side.
