### ISSUE TITLE
Older Kinect Compatibility

### ISSUE THREAD

**Issue by Fuadex** [keijiro/Akvfx#6]
Hi, I've got a question as to whether this will only work with Azure Kinect as compared to older Kinects?

And if it doesn't, what work would need to be done to get it up and running on older Kinects?

**Comment by keijiro** [comment]
There is no API level compatibility between Azure Kinect and other old Kinect models. You have to re-implement the entire driver for these older devices.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
