### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by amandalangley** [keijiro/Akvfx#7]
Hey, thanks for the awesome work! When I open the project, I am having a problem with resolving dependencies.  I'm getting a 502 error. My Azure Kinect is working on my computer. I have the correct Unity version 2019.2.2f1.

Here is what happens when I open the project:
![UnityErrorWhileOpeningProject](https://user-images.githubusercontent.com/36175508/66529867-f7473880-eab9-11e9-8275-a6d1f7d93504.png)

And this is what happens when I try and look at the Package Manager UI:
![PackageManagerError](https://user-images.githubusercontent.com/36175508/66530112-3aee7200-eabb-11e9-8f3b-5d703ed18ae4.PNG)

Any idea what is going on?

**Comment by keijiro** [comment]
This project uses the [UnityNuGet](https://github.com/xoofx/UnityNuGet/blob/master/registry.json) registry to import some Nuget packages. It seems the registry site is temporarily unavailable.

**Comment by sokobanni** [comment]
Looks like UnityNuGet doesn't work with 2019.2 (they said it only work with 2019.1), but recent akvfx project is set for 2019.2.2f.
In my case, after I tried to run it with 2019.1.14f, it will works fine with 2019.2.

**Comment by amandalangley** [comment]
> Looks like UnityNuGet doesn't work with 2019.2 (they said it only work with 2019.1), but recent akvfx project is set for 2019.2.2f.
> In my case, after I tried to run it with 2019.1.14f, it will works fine with 2019.2.

Hey, thanks, I've got it working now.
