### ISSUE TITLE
The hair obtained through the equipment is incomplete

### ISSUE THREAD

**Issue by jimzou** [keijiro/Akvfx#8]
Thank you for sharing. The hair obtained through the equipment is incomplete, which is more complete in your video. What is the best way to solve this problem?

**Comment by keijiro** [comment]
Honestly speaking, I don't have any idea about it. I'm not a specialist of volumetric video recording. Although my video looks good, it's just by chance. I'd recommend looking for a specialist who can give proper advice.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
